// THIS FILE IS AUTOMATICALLY GENERATED.
// It is recommended to not modify it directly.
// Instead, modify the original file in `hooks/use-toast.ts`

export { useToast, toast } from "@/hooks/use-toast"

